from storageinventory import InventoryStorageEdit
from storageinventory import InventoryStorageView
from storageinventory import PositionsView
from storageinventory import InventoryGraph
from ajax import StorageInventorySubmit
from ajax import InventoryPositionsInfo
from ajax import InventoryItemInfo