version: "2"
services:
  haproxy:
    image: eeacms/haproxy
    ports:
    - 8080:5000
    - 1936:1936
    depends_on:
    - baobab_lims_plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"

  baobab_lims_plone:
    build: .
    depends_on:
    - zeoserver
    environment:
    - ZEO_ADDRESS=zeoserver:8080

  zeoserver:
    build: .
    command: zeo
    volumes:
    - data:/data

volumes:
  data:
