from productsupplierswidget import ProductSuppliersView
from productsupplierswidget import ProductSuppliersWidget
from projectanalyseswidget import ProjectAnalysesView
from projectanalyseswidget import ProjectAnalysesWidget

